
  # ----------------------------------------
  # 1. BACKEND SERVICE
  # ----------------------------------------
  #- type: web
    name: backend-movie
    env: docker
    rootDir: ./backend-movie
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: SERVER_PORT
        value: "8080"
      - key: PORT
        value: "8080"
      - key: SPRING_DATA_MONGODB_URI
        value: "mongodb+srv://movie_microservices:microservices@cluster0.ttgcs.mongodb.net/movieMicroservice?appName=Cluster0"

  # ----------------------------------------
  # 2. FRONTEND SERVICE
  # ----------------------------------------
  - type: web
    name: frontend-movie
    env: docker
    rootDir: ./frontend-movie
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      # ⚠️ CRITICAL FIX: This CANNOT be localhost on Render!
      # When your app is on the internet, localhost means the user's personal laptop.
      # You MUST put the live web address of your backend here once Render creates it.
      - key: VITE_API_BASE_URL
        value: "http://localhost:8080"